    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction Note
      description: API to update the note of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to update the note for
        - in: body
          name: body
          description: Transaction note update payload
          required: true
          schema:
            $ref: '#/definitions/NotePayload'
      produces:
        - application/json
      responses:
        '200':
          description: Note updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete Transaction Note
      description: API to delete the note of a specific transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID of the transaction to delete the note from
      produces:
        - application/json
      responses:
        '200':
          description: Note deleted successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
